server_port: "8000"

tokens_ttl:
  jwt: 15m
  refresh: 240h

cookie:
  name: "refresh-token"
  age: 864000
  path: "/auth"
  domain: "localhost"
  secure: false
  http_only: true

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
